config/routes.rb
Rails.application.routes.draw do

  	get "sign_up", to: "users#new", as: :sign_up
	post "sign_up", to: "users#create"
	get "login", to: "sessions#new", as: :login
	post "login", to: "sessions#create"
	delete "logout", to: "sessions#destroy", as: :logout
	get "edit_profile", to: "users#edit"
	patch "edit_profile", to: "users#update"

	resources :posts do
		resources :likes
		resources :comments
	end

	resources :categories, except: [:show] do
		get 'posts/:id', to: 'categories#show', on: :collection, as: :category_posts 
	end


  	get 'welcome/index'
	get 'users/:user_id/my_posts', to: 'posts#my_posts'

	root 'welcome#index', as: :authenticated_root

	get '*path', to: 'application#page_not_found'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    before_save :downcase_email
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

    has_many :posts
    has_many :comments
    has_many :likes, dependent: :destroy
    
private
    def downcase_email
        self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to login_path, notice: "Account created"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def new
        @user = User.new
    end 

    def edit
        @user = current_user
    end

    def update
        @user = current_user

        if @user.update(user_params)
            redirect_to authenticated_root_url
        else
            render 'edit'
        end
    end

private
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="comment-form">
  <h2>Edit User</h2>
  <%= form_for(@user, url: edit_profile_path, method: :patch, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :username %><br />
      <%= form.text_field :username, autofocus: true, autocomplete: "username", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :email %><br />
      <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password %><br />
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div class="button-container">
      <%= form.submit "Edit user", class: "like-button" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="comment-form">
  <h2>Sign Up</h2>
  <%= form_with model: @user, url: sign_up_path, local: true, html: { class: "category-form" } do |form| %>
    <%= render partial: "shared/form_errors", locals: { object: form.object } %>
    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, required: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, required: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, required: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, required: true, class: "form-control" %>
    </div>
    
    <div class="button-container">
      <%= form.submit "Sign Up", class: "like-button" %>
    </div>
  <% end %>
</div>