config/routes.rb
Rails.application.routes.draw do

  	get "sign_up", to: "users#new", as: :sign_up
	post "sign_up", to: "users#create"
	get "login", to: "sessions#new", as: :login
	post "login", to: "sessions#create"
	delete "logout", to: "sessions#destroy", as: :logout
	get "edit_profile", to: "users#edit"
	patch "edit_profile", to: "users#update"

	resources :posts do
		resources :likes
		resources :comments
	end

	resources :categories, except: [:show] do
		get 'posts/:id', to: 'categories#show', on: :collection, as: :category_posts 
	end


  	get 'welcome/index'
	get 'users/:user_id/my_posts', to: 'posts#my_posts'

	root 'welcome#index', as: :authenticated_root

	get '*path', to: 'application#page_not_found'
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    validates :description, presence: true, length: { minimum: 5 }

    has_and_belongs_to_many :categories
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :user_signed_in?, except: [:index, :show]
    before_action :correct_user, only: [:edit, :update, :destroy]
    before_action :find_post, only: [:show, :edit, :update, :destroy]

    def index
        @posts = Post.all
    end

    def show
    end
    
    def edit
    end

    def update
        if @post.update(post_params)
            create_or_delete_posts_categories(@post, post_params[:category_ids])

            redirect_to @post
        else
            render 'edit'
        end
    end

    def new
        @post = current_user.posts.build
    end
    
    def create
        @post = current_user.posts.build(post_params)
        create_or_delete_posts_categories(@post, post_params[:category_ids])

        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def destroy
        @post.destroy

        redirect_to request.referer.present? ? request.referer : posts_path
    end

    def my_posts
        @post = Post.find_by(user_id: params[:user_id])
    end

    def correct_user
        @post = current_user.posts.find_by(id: params[:id]) unless current_user.nil?
        redirect_to request.referer.present? ? request.referer : posts_path, notice: "Not authorized" if @post.nil?
    end

private
    def create_or_delete_posts_categories(post, categories)
        post.categories.destroy_all
        
        unless categories.nil?
            categories.each do |category|
                if category.present?
                    new_category = Category.find(category)
        
                    post.categories << new_category
                end
            end
        end
    end

    def post_params
        params.require(:post).permit(:title, :description, :user_id, :category_ids => [])
    end

    def find_post
        begin 
            @post = Post.find(params[:id])
        rescue ActiveRecord::RecordNotFound => e
            redirect_to '/500'
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_script.html.erb
<script>
    document.querySelectorAll('.post-nav').forEach(function(element) {
        element.className += ' active'
    });
</script>

app/views/posts/edit.html.erb
<div class="comment-form">
    <h2>Edit Post</h2>
    <%= form_with model: @post, local: true do |form| %>
        <% if @post.errors.any? %>
            <div id="error_explanation">
                <h2>
                    <%= pluralize(@post.errors.count, "error") %> prohibited
                    this post from being saved:
                </h2>
                <ul>
                    <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <%= hidden_field_tag(:_method, :patch) %>

        <div class="form-group">
            <%= form.label :title %><br>
            <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= form.label :description %><br>
            <%= form.text_field :description, class: "form-control" %>
        </div>

        <%= form.hidden_field :likes, value: @post.likes %>

       <div class="change-categories">
            <div>Change categories</div>
            </br>
            <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :title) do |cd| %>
                <div class="checkbox-container">
                <label class="custom-checkbox-label">
                    <%= cd.check_box class: "custom-checkbox" %>
                    <%= cd.label %>
                </label>
                </div>
            <% end %>
        </div>

        </br>
        <div class="button-container">
            <%= form.submit "Submit", class: "like-button" %>
        </div>
    <% end %>
</div>

<%= render 'script' %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <p class="button-container", style="text-align: right;">
    <%= link_to 'Add post', new_post_path, class: "like-button" %>
  </p>
<% end %>

<h1 class="category_title">Posts</h1>

<div class="post-container">
  <% @posts.each do |post| %>
    <% if (!current_user.nil? && post.user_id != current_user.id) || current_user.nil? %>
      <div class="post">
        <div class="post-title"><%= post.title %></div>
        <div class="post-description"><%= post.description %></div>
        <div><%= (post.likes.count) == 1 ? 'Like:' : 'Likes:'%><%= post.likes.count %></div>

        <div class="post-actions">
          <%= link_to 'Show', post_path(post) %>

          <% if user_signed_in? %>
            <div class="like-button">
              <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
              <% else %>
                <%= button_to 'Like', post_likes_path(post), method: :post %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<script>
    const likeButtons = document.querySelectorAll('.like-button');

    likeButtons.forEach(button => {
      button.addEventListener('click', function () {
        const postId = this.getAttribute('data-post-id');
        likePost(postId);
      });
    });

    function likePost(postId) {
      fetch(`/posts/${postId}/like`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
        },
      })
      .then(response => response.json())
      .then(data => {
        const likeCountElement = document.querySelector(`.like-count-${postId}`);
          likeCountElement.textContent = "Likes: " + data.likes;
        
      })
      .catch(error => {
        console.error('Error liking post:', error);
      });
    }

</script>

<%= render 'script' %>

app/views/posts/my_posts.html.erb
<% if user_signed_in? %>
  <p class="button-container", style="text-align: right;">
    <%= link_to 'Add post', new_post_path, class: "like-button" %>
  </p>
<% end %>

<h1 class="category_title">Posts</h1>

<div class="post-container">
  <% user = User.find_by_id(params[:user_id]) %>
  <% user.posts.each do |post| %>
    <div class="post">
      <div class="post-title"><%= post.title %></div>
      <div class="post-description"><%= post.description %></div>
      <div><%= (post.likes.count) == 1 ? 'Like:' : 'Likes:'%><%= post.likes.count %></div>
      <div class="post-actions">
        <%= link_to 'Show', post_path(post) %>
        <div class="like-button">
          <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
          <% else %>
            <%= button_to 'Like', post_likes_path(post), method: :post %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
    document.querySelectorAll('.my-posts-nav').forEach(function(element) {
        element.className += ' active'
    });
</script>

app/views/posts/new.html.erb
<h2 class="category_title">New Post</h2>

<%= form_with scope: :post, url: posts_path, local: true, html: { class: "category-form" } do |form| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@post.errors.count, "error") %> prohibited
                this post from being saved:
            </h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="form-group">
        <%= form.label :title, class: "form-label" %><br>
        <%= form.text_field :title, class: "form-control" %>
    </div>
 
    <div class="form-group">
        <%= form.label :description, class: "form-label" %><br>
        <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.number_field :user_id, id: :post_user_id, class: "form-control", value: current_user.id, type: :hidden %>
    </div>
    
    <div class="change-categories">
        <div>Change categories</div>
        </br>
        <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :title, :include_hidden => false ) do |cd| %>
            <div class="checkbox-container">
            <label class="custom-checkbox-label">
                <%= cd.check_box class: "custom-checkbox" %>
                <%= cd.label %>
            </label>
            </div>
        <% end %>
    </div>

    <div class="button-container">
        <%= form.submit "Submit",class: "like-button" %>
    </div>
<% end %>

<%= render 'script' %>

app/views/posts/show.html.erb
<div class="button-container", style="text-align: left;">
   <%= link_to 'Back', request.referer.present? ? request.referer : posts_path, class: "like-button" %>
</div>

<div class="post">
  <h1>
    <%= @post.title %>
  </h1>
  
  <p>
    <strong>Posted by:</strong>
    <%= User.find_by(id: @post.user_id).username %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @post.description %>
  </p>
  
  <p>
    <%= (@post.likes.count) == 1 ? 'Like:' : 'Likes:'%>
    <%= @post.likes.count %> 
  </p>
  
  <p>
    <% if @post.categories.present? %>
      <strong>Categories:</strong> 
      <% @post.categories.each do |category| %>
        <%= category.title %>
      <% end %>
    <% end %>
  </p>

  <div class="post-actions">
    <%= link_to 'Edit', edit_post_path(@post), class: "links" %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" %>
  </div>

  <% if user_signed_in? %>
    <div class="like-button">
      <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
      <% if pre_like %>
        <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
      <% else %>
        <%= button_to 'Like', post_likes_path(@post), method: :post %>
      <% end %>
    </div>
  
    <div class="comment-form">
    <h2>Add Comment:</h2>
      <%= form_with(model: [@post, @post.comments.build], local: true) do |form| %>
        <div class="form-group">
          <%= form.text_field :commenter, class: "form-control", value: "fhdsfh", type: :hidden %>
        </div>

        <div class="form-group">
          <%= form.label :text %><br>
          <%= form.text_area :text, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= form.number_field :user_id, id: :comment_user_id, class: "form-control", value: 0, type: :hidden %>
        </div>

        <div class="button-container">
          <%= form.submit "Submit", class: "like-button" %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% comment_limit = user_signed_in? ? 1 : 0 %>
  <% if @post.comments.length > comment_limit %>
    <div class="post-comment-box">
      <h2>Comments:</h2>
      <% @post.comments.each do |comment| %>
        <% if !comment.commenter.nil? && !comment.text.nil? %>
          <div class="comment">
            <p>
              <strong>Commenter:</strong>
              <%= comment.commenter %>
            </p>
          
            <p>
              <strong>Comment:</strong>
              <%= comment.text %>
            </p>
          
            <div class="comment-actions">
              <%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" %>
            </div>
            </br>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>  

<%= render 'script' %>