config/routes.rb
Rails.application.routes.draw do

  	get "sign_up", to: "users#new", as: :sign_up
	post "sign_up", to: "users#create"
	get "login", to: "sessions#new", as: :login
	post "login", to: "sessions#create"
	delete "logout", to: "sessions#destroy", as: :logout
	get "edit_profile", to: "users#edit"
	patch "edit_profile", to: "users#update"

	resources :posts do
		resources :likes
		resources :comments
	end

	resources :categories, except: [:show] do
		get 'posts/:id', to: 'categories#show', on: :collection, as: :category_posts 
	end


  	get 'welcome/index'
	get 'users/:user_id/my_posts', to: 'posts#my_posts'

	root 'welcome#index', as: :authenticated_root

	get '*path', to: 'application#page_not_found'
end

app/models/category.rb
class Category < ApplicationRecord
    validates :title, presence: true, length: { minimum: 3 }
    has_and_belongs_to_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    begin
      @category = Category.new(category_params)

      if @category.save
        redirect_to categories_path
      else
        render 'new'
      end
    rescue ActiveRecord::RecordNotUnique => e
      redirect_to '/500'
    end

    
  end

  def update
    if @category.update(category_params)
      redirect_to category_posts_categories_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    post = @category.posts

    if post
      @category.posts.delete
    end

    @category.destroy
    redirect_to categories_path
  end

  private
    def set_category
      begin
        @category = Category.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to '/500'
      rescue ActiveRecord::RecordNotUnique => e
        redirect_to '/500'
      end
    end

    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_script.html.erb
<script>
    document.querySelectorAll('.category-nav').forEach(function(element) {
        element.className += ' active'
    });
</script>

app/views/categories/edit.html.erb
<h2 class="category_title">Edit Category</h2>


<%= form_with scope: :category, url: category_path(@category), html: { class: "category-form" } do |form| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@category.errors.count, "error") %> prohibited
                this post from being saved:
            </h2>
            <ul>
                <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="form-group">
        <%= form.label :title, class: "form-label" %><br>
        <%= form.text_field :title, class: "form-control" %>
    </div>

    <input type="hidden" name="_method" value="patch">
    <div class="button-container">
        <%= form.submit "Submit", class: "like-button" %>
    </div>
    
<% end %>

<%= render 'script' %>

app/views/categories/index.html.erb
<% if user_signed_in? %>
    <div class="button-container", style="text-align: right;">
        <%= link_to 'Add Category', new_category_path, class: "like-button" %>
    </div>
<% end %>

<h1 class="category_title">Categories</h1>

<div class="categories">
    <% @categories.each do |category| %>
        <%= link_to category.title, "/categories/posts/#{category.id}", class: "links" %>
    <% end %>
</div>

<%= render 'script' %>

app/views/categories/new.html.erb
<h2 class="category_title">New Category</h2>

<%= form_with scope: :category, url: categories_path, local: true, html: { class: "category-form" } do |form| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@category.errors.count, "error") %> prohibited
                this post from being saved:
            </h2>
            <ul>
                <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="form-group">
        <%= form.label :title, class: "form-label" %><br>
        <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="button-container">
        <%= form.submit "Submit", class: "like-button" %>
    </div>
<% end %>

<%= render 'script' %>

app/views/categories/show.html.erb
<div class="button-container", style="text-align: left;">
   <%= link_to 'Back', request.referer.present? ? request.referer : categories_path, class: "like-button" %>
</div>

<h1 class="category_title"><%= @category.title %></h1>

<div class="post-actions">
    <%= link_to 'Edit', edit_category_path(@category), class: "links" %>
    <%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" %>
</div>

<div class="post-container">
  <% @category.posts.each do |post| %>
    <div class="post">
      <div class="post-title">
        <%= link_to post.title, post_path(post) %>
      </div>

      <div class="post-actions">
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'script' %>